# File: docker-compose.yml
version: '3.8'

services:

  # --- 1. The API Service ---
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DSN=postgresql://user:password@postgres/db
      - REDIS_DSN=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app

  # --- 2. The Background Worker Service ---
  worker:
    build: ./worker
    environment:
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    volumes:
      - ./worker:/app

  # --- 3. The PostgreSQL Database Service ---
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # --- 4. The Redis Queue Service ---
  redis:
    image: redis:7-alpine
volumes:
  postgres_data:

